### PR TITLE
#97 draft add coverage

### LINKED ISSUE #97: Add code coverage
**Is your feature request related to a problem? Please describe.**

We would like to generate code coverage metrics

**Describe the solution you would like**

- Add code coverage plugin to SBT
- Generate the coverage report
- Somehow make it visible in the PR / build

### PR DESCRIPTION
**Pull request by havryliuk**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

1. Use `sbt-jacoco` plugin to calculate coverage.
2. Set current coverage thresholds for modules `server` and `cli`
3. If coverage thresholds are not met, the build will fail.

Fixes #97

### CODE REVIEW

**Comment by tdas** [comment]
This is awesome. thank you. Where will generate the report? in the build output?

**Comment by tdas** [comment]
If so, is it possible to make it more visible, like posted on the PR.

**Comment by tdas** [comment]
I dont see the coverage report posted in the build either. 
can you post it somehow?

**Comment by havryliuk** [comment]
Coverage files are not generated during `build/sbt clean coverage test`. Investigating...

**Comment by havryliuk** [comment]
@tdas I think this one is complete. Let me know if you have any questions.

Here is a sample pipeline with failed coverage: https://github.com/unitycatalog/unitycatalog/actions/runs/9740280621/job/26877074027?pr=99

image

**Comment by tdas** [comment]
Thank you! I dont think we can affort right now to fail builds with thresholds. So can you remove the thresholds? All I want to make sure is that the code coverage per project gets printed somewhere so that we know where we stand.

**Comment by havryliuk** [comment]
@tdas sure but it will take more time
I think it's possible to show coverage as a badge on the README page. Do you think it's fine?
Or just printing it in the log is enough?
I will investigate other alternatives.

**Comment by vikrantpuppala** [comment]
@havryliuk the most ideal way would be to have it as a comment on the PR. Would it be a lot of work?
Something like `main` has coverage x% vs this PR has coverage y% would be even more great but that might require more work so we can iterate and improve to reach that stage.

**Comment by tdas** [comment]
I like @vikrantpuppala suggestion but it's going to take more work. So let's me merge this PR since this is much better than nothing. And then lets do those improvements in a follow up PR?

**Review by tdas — APPROVED** [review]

**Comment by tdas** [comment]
and thank you @havryliuk for picking this up.

**Pull request merged**
