### PR TITLE
docs: update functions page

### LINKED ISSUE #140: docs: build out functions documentation page
built out the functions page in the documentation.

### PR DESCRIPTION
**Pull request by avriiil**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

This PR updates the Functions docs page with more explanations and additional examples. This will close #140

### CODE REVIEW

**Comment by avriiil** [comment]
@MrPowers - this is ready for review. looks like there's a test failing related to auth permissions (?) -- is that something I should fix on my side?

**Comment by vikrantpuppala** [comment]
you're good @avriiil, this is broken workflow that we'll fix

**Comment by MrPowers** [comment]
This is fun:

```
bin/uc function create --full_name unity.default.myPythonFunction --data_type INT --input_params "n_sides int, n_dice int" --language "python" --def "import numpy as np\nrolls=np.random.randint(1, n_sides + 1, size=n_dice)\nreturn print(rolls)"
```

But is this considered good or bad?  I actually don't know.

**Review by MrPowers — APPROVED** [review]
LGTM

**Pull request merged**
