### PR TITLE
Bump sbt-openapi-generator to v7.9.0

### PR DESCRIPTION
**Pull request by jaceklaskowski**
Bump sbt-openapi-generator to the latest version [v7.9.0](https://github.com/OpenAPITools/sbt-openapi-generator/releases/tag/v7.9.0).

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
@tdas @dennyglee Can you review (and accept)? 🙏

**Comment by dennyglee** [comment]
Hey @jaceklaskowski  - it's a cool enough fix but curious as to why you feel the bump is required?  Looking at the `openapi-generator` [releases](https://github.com/OpenAPITools/openapi-generator/releases), nothing seems to stand out.  But please correct me if I'm missing something, eh?!

**Comment by jaceklaskowski** [comment]
@dennyglee You're entirely correct, mate 👍  There is nothing that would beg the upgrade other than I found this new version on their site and thought I'd upgrade 🤷‍♂️ 

Feel free to close it if it's not worth a commit. I'm OK either way.

**Comment by jaceklaskowski** [comment]
@dennyglee 🙏

**Review by Fokko — APPROVED** [review]

**Review by dennyglee — APPROVED** [review]

**Pull request merged**
