### PR TITLE
Restrict the object names allowed characters to a smaller, more common set.

### PR DESCRIPTION
**Pull request by creechy**
**PR Checklist**

- [X] A description of the changes is added to the description of this PR.
- [X] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

This change restricts object names to a smaller, more common character-set - a-z, A-Z, 0-9, _(underscore), @(at sign) and -(hyphen).  

Resolves Issue https://github.com/unitycatalog/unitycatalog/issues/185

### CODE REVIEW

**Review by vikrantpuppala — APPROVED** [review]
@haogang to merge

**Review by haogang — APPROVED** [review]
lgtm. please resolve conflicts.

**Comment by creechy** [comment]
@haogang 

> lgtm. please resolve conflicts.

done.

**Comment by ravivj-db** [comment]
Can we please add some more test cases for the changes in this PR : https://github.com/unitycatalog/unitycatalog/blob/main/server/src/test/java/io/unitycatalog/server/utils/SqlNameValidationTest.java

**Pull request merged**
