### PR TITLE
Introduce AssertJ for testing

### LINKED ISSUE #77: Introduce AssertJ for testing
It would be great to use [AssertJ](https://assertj.github.io/doc/)-style assertions for testing as those are more fluent and provide greater flexibility when asserting and testing code

### PR DESCRIPTION
**Pull request by nastra**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

This introduces the AssertJ library for a more fluent way of testing and asserting things. This library is widely used and improves reading and testing code (it's also being used in the Iceberg codebase).

I took the libery to convert the `IcebergRestCatalogTest` to AssertJ assertions to show its fluent nature.

fixes #77

### CODE REVIEW

**Comment by Cupprum** [comment]
The [Readme.md testing section](https://github.com/unitycatalog/unitycatalog?tab=readme-ov-file#compiling-and-testing) mentions, that the following command should be used to start tests `build/sbt clean test`.

However if I understand it correctly, only the cli tests are being executed.
Maybe its somehow connected to [this](https://github.com/unitycatalog/unitycatalog/blob/02ec950bf341390d6ca2c4b334257e36f02133cf/build.sbt#L52-L53)?

**Comment by nastra** [comment]
@Cupprum yould you please elaborate on your comment as I'm not fully following what you're referring to in the context of this PR

**Comment by Cupprum** [comment]
I wanted to verify your changes locally on my machine. As you were working on updating the tests, i wanted to try to run them locally. When I try to do so using the previously mentioned documentation, it seems like the proper tests are not being executed.

**Comment by nastra** [comment]
@Cupprum the tests run fine on my end when executing `build/sbt clean test` as can be seen below
```
[info] Test run io.unitycatalog.server.iceberg.IcebergRestCatalogTest started
[info] Test io.unitycatalog.server.iceberg.IcebergRestCatalogTest.testTable[0] started
[info] Test io.unitycatalog.server.iceberg.IcebergRestCatalogTest.testNamespaces[0] started
[info] Test io.unitycatalog.server.iceberg.IcebergRestCatalogTest.testTableExistsInvalidNamespace[0] started
[info] Test io.unitycatalog.server.iceberg.IcebergRestCatalogTest.testLoadTablesInvalidNamespace[0] started
[info] Test io.unitycatalog.server.iceberg.IcebergRestCatalogTest.testConfig[0] started
[info] Test io.unitycatalog.server.iceberg.IcebergRestCatalogTest.testListTablesInvalidNamespace[0] started
[info] Test run io.unitycatalog.server.iceberg.IcebergRestCatalogTest finished: 0 failed, 0 ignored, 6 total, 12.864s
```

I think previously the tests were just not being shown and this was fixed by #71

**Comment by nastra** [comment]
@tdas could you take a look please?

**Comment by Cupprum** [comment]
Thanks a lot for providing the command which you use for testing and also for an explanation.

I agree that the tests show green light, but when i execute tests on your fork (and it was like that on blessed branch when we started this discussion as well), they seem to finish much faster, compared to the time of executing tests on current main.

**Review by tdas — APPROVED** [review]

**Comment by tdas** [comment]
This is awesome. Thank you for clarifying in the issue why this is the new standard used by other projects. I agree, lets start using assertJ. 

cc @ravivj-db @vikrantpuppala please take note and lets starting using assertJ from now on.

**Pull request merged**
