### PR TITLE
add close InputStream

### PR DESCRIPTION
**Pull request by 597365581**
add close InputStream

**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

### CODE REVIEW

**Comment by 597365581** [comment]
@tdas add close InputStream because this InputStream  need to cloase when use over

**Review by vikrantpuppala — COMMENTED** [review]
The existing code uses the try-with-resources statement to auto close the input stream. I'm not sure if there is something else I'm missing.

**Comment by tdas** [comment]
@597365581 if there is not improvement needed, then can you close this PR? Thank you for your interest in contributing!

**Comment by vikrantpuppala** [comment]
Closing this PR for now, please feel free to open, thanks!

**Pull request closed without merging**
