### PR TITLE
docs: Apache XTable Guide for Unity Catalog

### PR DESCRIPTION
**Pull request by dipankarmazumdar**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've added or modified a feature, documentation in `docs` is updated

Resolves this issue - https://github.com/unitycatalog/unitycatalog/issues/160

- Documentation change only

### CODE REVIEW

**Comment by dennyglee** [comment]
Thanks @dipankarmazumdar - will review this shortly!

**Review by dennyglee — DISMISSED** [review]

**Comment by MrPowers** [comment]
Thanks for submitting this @dipankarmazumdar!!

**Comment by dipankarmazumdar** [comment]
Thanks @dennyglee for reviewing. Addressed the comments!

**Review by MrPowers — APPROVED** [review]
LGTM!

**Pull request merged**
