### PR TITLE
Fix list max results

### PR DESCRIPTION
**Pull request by vksx**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

Added bugfix for `list --max_results` using PagedListingHelper as recommended [here](https://github.com/unitycatalog/unitycatalog/pull/271#discussion_r1693351596).

cc: @vikrantpuppala

### CODE REVIEW

**Comment by vikrantpuppala** [comment]
Thank you! could you fix the unit tests please?

**Comment by vksx** [comment]
@vikrantpuppala Fixed.

**Comment by vikrantpuppala** [comment]
thank you, however, the tutorial tests seem to be failing now, can you please check why?

**Comment by vksx** [comment]
The error is:
> Waiting... Failed to connect to the server: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f66590a9100>: Failed to establish a new connection: [Errno 111] Connection refused'))

I just tested this - working fine in local. I will take a look.

**Comment by vksx** [comment]
Decided to just do an empty commit to retrigger the workflow - seems like it's working now. Must have been some intermittent issue.

**Review by vikrantpuppala — APPROVED** [review]
thank you!

**Comment by vikrantpuppala** [comment]
@haogang to merge

**Review by haogang — APPROVED** [review]

**Pull request merged**
