### PR TITLE
upgrade to setup-java v4

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by tdas** [comment]
What is the benefits between v3 and v4?

**Comment by tdas** [comment]
@sullis any thoughts? I just want to understand the impact of a change befoer merging it.

**Comment by sullis** [comment]
> @sullis any thoughts? I just want to understand the impact of a change befoer merging it.

setup-java v4 release notes are available here:

https://github.com/actions/setup-java/releases

**Comment by tdas** [comment]
@sullis thank you. I see that this just makes it more future proof to future versions of java (e.g. 21). thanks. merging it.

**Pull request merged**
