### PR TITLE
Checkstyle configfix and last style error fixed

### PR DESCRIPTION
**Pull request by alcole**
**PR Checklist**

- [x ] A description of the changes is added to the description of this PR.
- [x ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

https://github.com/unitycatalog/unitycatalog/issues/98

last of the checkstyle issues in the examples locations

1. added line starting blank then a " in the regex to ignore config lines
2. added braces to CliUtils file to fix remaining checkstyle error

### CODE REVIEW

**Review by vikrantpuppala — APPROVED** [review]
@haogang to merge

**Comment by vikrantpuppala** [comment]
@haogang ping on this as well

**Comment by monamohan** [comment]
@creechy  @alexreid-db  to review

**Comment by alexreid-db** [comment]
This was actually addressed already in https://github.com/unitycatalog/unitycatalog/pull/317

**Pull request closed without merging**
