### PR TITLE
Updated README for setting up and using a virtual env

### PR DESCRIPTION
**Pull request by arslanaka**
…rtual environment (uc_docs_venv)

**PR Checklist**

- [ ] A description of the changes is added to the description of this PR.
- [ ] This PR is related to issue [https://github.com/unitycatalog/unitycatalog/issues/111#issue-2381931073](url)

**Description of changes**

Enhanced README with detailed setup instructions for creating and using a virtual environment named 'uc_docs_venv' to facilitate smoother usage.

### CODE REVIEW

**Comment by tdas** [comment]
Thank you for the clarification. @MrPowers does this update make sense?

**Review by MrPowers — APPROVED** [review]
LGTM, thanks @arslanaka

**Comment by MrPowers** [comment]
Fixes #111

**Comment by tdas** [comment]
Thank you @arslanaka Merging this this.

**Review by tdas — APPROVED** [review]

**Pull request merged**
