### PR TITLE
build/sbt javafmtAll on io.unitycatalog.server.persist and io.unitycatalog.server.service package

### PR DESCRIPTION
**Pull request by nastra**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

build/sbt javafmtAll on `io.unitycatalog.server.persist` and `io.unitycatalog.server.service` package

### CODE REVIEW

**Comment by haogang** [comment]
Do you run the formatting manually? Instead of merging PRs like this manually now and then in the future, can we make formatting part of the unit test and block merging future PRs without proper formatting?

**Comment by nastra** [comment]
Yes, currently I'm running the formatting manually via `build/sbt javafmtAll` but long term we might want to either run the formatting as part of compilation or complain during/after compilation that the code isn't properly formatted. 
@tdas suggested that we first get the formatting right in the existing codebase, which is the scope of this and a few other PRs to make reviewing not too difficult

**Comment by nastra** [comment]
@ravivj-db done

**Review by ravivj-db — APPROVED** [review]

**Comment by ravivj-db** [comment]
Related to issue : https://github.com/unitycatalog/unitycatalog/issues/98

**Pull request merged**
