### PR TITLE
Fix my own mistake in the last PR

### PR DESCRIPTION
**Pull request by SemyonSinchenko**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

In #151 I made a mistake and it was before duckdb tests were introduced. This PR is a fix.

@ravivj-db Sorry, it was may mistake. May you take a look, please?

### CODE REVIEW

**Review by ravivj-db — APPROVED** [review]
LGTM

**Comment by ravivj-db** [comment]
There's also a concern that tests are failing in the main branch : https://github.com/unitycatalog/unitycatalog/actions/runs/9974656539/job/27562593952 .. can you please check up on that .. is it related to this PR ?

**Comment by SemyonSinchenko** [comment]
> There's also a concern that tests are failing in the main branch : https://github.com/unitycatalog/unitycatalog/actions/runs/9974656539/job/27562593952 .. can you please check up on that .. is it related to this PR ?

It is. And the PR is a fix.

**Comment by vikrantpuppala** [comment]
@haogang this will fix the duckdb tests, can you merge please

**Review by haogang — APPROVED** [review]

**Pull request merged**
