### PR TITLE
Remove generated code from repo and generate it compile time

### PR DESCRIPTION
**Pull request by vikrantpuppala**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

Remove generated code from the repo and rather generate it compile time

### CODE REVIEW

**Review by rameshchandra — CHANGES_REQUESTED** [review]
@vikrantpuppala thank you for making this change.

Since the generated files are generated as part of the build process, the `target` dir is a better location for them instead of the `src` directory. With this no new rules are needed for gitignore and `sbt clean` cleans up the generated files (currently the generated files stick around after a `sbt clean`).

Also, when are the files regenerated? are they regenerated on an incremental build when the yaml file changes?

**Review by rameshchandra — APPROVED** [review]
LGTM

**Review by haogang — APPROVED** [review]
lgtm. please address conflict.

**Comment by creechy** [comment]
@vikrantpuppala 

> lgtm. please address conflict.

I poked around at this a little bit. I think to fix the tab ball creation all you have to do is to change `projectJarFiles` in `Tarball.scala` to 
```
        val projectJarFiles = Seq(
          (LocalProject("serverModels") / Compile / packageBin).value.getAbsoluteFile,
          (LocalProject("server") / Compile / packageBin).value.getAbsoluteFile,
          (LocalProject("cli") / Compile / packageBin).value.getAbsoluteFile,
          (LocalProject("client") / Compile / packageBin).value.getAbsoluteFile,
        )
```

that is, just move "serverModels" first.

**Comment by vikrantpuppala** [comment]
Thanks @creechy, I tried that (and a bunch of other things) but still couldn't get this to work. It always fails in a clean env. Once models are generated, it is able to resolve dependencies correctly (i.e. sbt compile|generate createTarball works or even running createTarball two times).. hence, feel like there is something i'm missing in the sbt build.

**Comment by vikrantpuppala** [comment]
@rameshchandra/@haogang this is ready to be merged.

**Pull request merged**
