### PR TITLE
Issue 98 checkstyle phase2 2

### PR DESCRIPTION
**Pull request by alcole**
**PR Checklist**

- [ ] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

applied the checkstyle error fixes 

second PR relating to phase 2 of this issue https://github.com/unitycatalog/unitycatalog/issues/98

I've tackled most of the easy wins, 4 to 2 spaces, long lines etc. This has removed most of the errors and only 140 remain. I can take a look at these in the next batch

### CODE REVIEW

**Review by tdas — APPROVED** [review]

**Comment by tdas** [comment]
sorry @nastra this is bane of large code refactor... high chance of conflicts. Could you resolve conflicts once again :(

**Comment by nastra** [comment]
@alcole I think what would make sense here is to run `build/sbt javafmtAll` rather than trying to manually do the indentation and the formatting. Could you please run that against these files? I've also added some docs on how to set up the code formatter for the IDE in https://github.com/unitycatalog/unitycatalog?tab=readme-ov-file#setting-up-ide in case you'd like to format the source code directly from the IDE (which will produce the same results as running `build/sbt javafmtAll`)

**Comment by tdas** [comment]
sorry @nastra .. i have been accidentally bugging you instead of @alcole . let try to fix this conflict and quickly merge this.

**Comment by alcole** [comment]
I'll take a look in the next day or so. I did have a quick check and it looked like the line wrapping where making the changes look bigger than they actually are. But I'll look into the conflicts that are flagged

@nastra I'll take a look, I saw the documentation was updated to include instructions here. It did look as though it was configured to run over more code than the check style setup was initially configured for, I wasn't sure if this was intentional.

So far it's been relatively easy to remove most of the errors using intellij.

**Comment by alcole** [comment]
@tdas conflicts are now resolved

**Comment by nastra** [comment]
@alcole I checked out your branch and ran `build/sbt javafmtAll` and it re-formatted the files you're touching in this PR. Can you please also run this command locally to make sure these files are properly formatted?

**Comment by alcole** [comment]
@tdas I've been working locally on my pc to try and resolve, I check in on this page and see that I have sent a force push without realising how. I've had a quick scan and I don't think I have the permissions to revert (I suspect that would be the safest thing to do). Let me know what I can do though and I will work it through

**Pull request closed without merging**
