### PR TITLE
Add uc_function_name to tools

### PR DESCRIPTION
**Pull request by serena-ruan**
**PR Checklist**

- [ ] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**
For these tools, we convert the original uc function name `catalog.schema.function` to `catalog__schema__function` (max length 64) to be compatible with OpenAI requirements, but sometimes we need to extract the original uc function name in the downstream usages. So saving the original uc function name directly to avoid any conversion error.

### CODE REVIEW

**Comment by serena-ruan** [comment]
@BenWilson2 to take a look :)

**Review by BenWilson2 — APPROVED** [review]
LGTM :) Good to have that extra metadata!

**Comment by serena-ruan** [comment]
Hi @dennyglee Could we merge this one :)

**Review by dennyglee — APPROVED** [review]
LGTM!

**Pull request merged**
