### PR TITLE
Restructuring UI into /ui folder

### PR DESCRIPTION
**Pull request by dennyglee**
**PR Checklist**

- [X] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**
Per #349 with the `unitycatalog-ui` repo (`main` branch) code-base as part of `unitycatalog` repo (`ui` branch), this next set of steps is to:
- Restructure the `ui` branch so that all code sits in the `/ui` folder ala
  ```
  | unitycatalog
  |- api
  |- ...
  |- tests
  |- ui (new)
     |- public
     |- src
     |- READMNE.md
     |- package.json
     |- ...
  ```

- Remove the following files as the `main` already has them and would supersede this anyways
  ```
  CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  LICENSE.txt
  ```
  
- In addition, the `link-checker.yaml` was moved the `/ui` folder and placed into `root` and updated so that it would only check the files in the `/ui` folder.

Going forward, the UI and the server are in the same repo and branch thus simplifying debugging, development, and deployment.

### CODE REVIEW

**Review by jamieknight-db — APPROVED** [review]
LGTM thank you @dennyglee

**Review by creechy — APPROVED** [review]
all contained in `ui/` makes sense.

**Comment by robertgv** [comment]
Nice work @dennyglee! 😄

**Comment by robertgv** [comment]
Just make sure you don't squash the PR and only merge it so that the commit history is preserved.

**Comment by dennyglee** [comment]
> Just make sure you don't squash the PR and only merge it so that the commit history is preserved.

@robertgv are you concerned that if we do a "squash and merge" that all 53 commits will be combined into one commit in the base branch?

**Comment by robertgv** [comment]
> > Just make sure you don't squash the PR and only merge it so that the commit history is preserved.
> 
> @robertgv are you concerned that if we do a "squash and merge" that all 53 commits will be combined into one commit in the base branch?

@dennyglee Correct. If we squash and merge, it will combine all the commits into a single commit on the base branch. If that's the goal, perfect. But if you want to keep track of all the commits from the UI repo on the base branch, don't do the squash.

**Comment by dennyglee** [comment]
> > > Just make sure you don't squash the PR and only merge it so that the commit history is preserved.
> > 
> > 
> > @robertgv are you concerned that if we do a "squash and merge" that all 53 commits will be combined into one commit in the base branch?
> 
> @dennyglee Correct. If we squash and merge, it will combine all the commits into a single commit on the base branch. If that's the goal, perfect. But if you want to keep track of all the commits from the UI repo on the base branch, don't do the squash.

@robertgv Ah got it, okay, let me redo this then.

**Pull request closed without merging**
