### PR TITLE
docs: add tutorial to nav

### PR DESCRIPTION
**Pull request by avriiil**
This PR adds the tutorial to the nav side-bar

### CODE REVIEW

**Comment by tdas** [comment]
Could you also add deployment to nav bar? then the tests will be fixed

**Comment by MrPowers** [comment]
Thanks for adding this!  Looks like we need to fix a couple of links and then this PR will be good-to-go!

**Comment by avriiil** [comment]
@MrPowers - this should be gtg now

**Review by MrPowers — APPROVED** [review]
LGTM

**Review by tdas — APPROVED** [review]

**Pull request merged**
