### PR TITLE
UC Swagger Implementation

### LINKED ISSUE #343: UC Swagger
**Is your feature request related to a problem? Please describe.**
We need to create UC swagger docs

**Describe the solution you would like**
Currently, the UC APIs can be found at https://go.unitycatalog.io/apidocs; we should update them to be swagger to simplify API development. 

**Additional context**

### PR DESCRIPTION
**Pull request by sudharshanraja-db**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**
 Added github actions to publish swagger  docs to github pages. This github action creates gh-pages branch and then pages sections in GH needs to be configured to point that branch to access the site.
closes #343

### CODE REVIEW

**Comment by sudharshanraja-db** [comment]
closes #343

**Comment by sudharshanraja-db** [comment]
@dennyglee  PR is ready for review

**Comment by sudharshanraja-db** [comment]
Attaching the screenshot 
uc_swagger

**Review by dennyglee — APPROVED** [review]
LGTM - thanks a bunch!

**Pull request merged**
