### PR TITLE
Enforce code style when compiling

### PR DESCRIPTION
**Pull request by nastra**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

This enforces the java code style when compiling.

The PR also contains formatting changes to a few classes that weren't adhereing to the code style.

This currently depends on https://github.com/unitycatalog/unitycatalog/pull/169 to remove the model classes from the `server` package as otherwise `javafmtCheckAll` complains about those files not being properly formatted

### CODE REVIEW

**Comment by vikrantpuppala** [comment]
lgtm, but not approving right now because of the dependency.

**Comment by vikrantpuppala** [comment]
Hi @nastra could you rebase this from main?

**Comment by nastra** [comment]
@vikrantpuppala I've rebased this and re-formatted missing files. This should be ready to go in now

**Review by vikrantpuppala — APPROVED** [review]
@haogang to merge

**Review by haogang — APPROVED** [review]

**Pull request merged**
