### PR TITLE
Add notebook sample for UCAI Langchain and OpenAI

### PR DESCRIPTION
**Pull request by serena-ruan**
**PR Checklist**

- [ ] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

### CODE REVIEW

**Comment by jaceklaskowski** [comment]
Can you convert the notebooks to pure python? 🙏  Code review is gonna be much easier 🤷

**Comment by jaceklaskowski** [comment]
BTW, where can I find some docs / a `README.md`-like description about how to import and run the notebooks?

**Comment by serena-ruan** [comment]
> Can you convert the notebooks to pure python? 🙏 Code review is gonna be much easier 🤷

Could you click on `view file` to review it? https://github.com/unitycatalog/unitycatalog/blob/0faaf579106c6721316f47e3000b18384e6f95d4/unitycatalog-ai/integrations/langchain/ucai-langchain_sample.ipynb

**Comment by serena-ruan** [comment]
> BTW, where can I find some docs / a `README.md`-like description about how to import and run the notebooks?

The top of the notebook mentioned we should import and run this notebook in Databricks. We can add a link once the docs page for the integrations packages lands

**Review by dennyglee — APPROVED** [review]

**Pull request merged**
