### PR TITLE
Adding analytics plugin for mkdocs

### PR DESCRIPTION
**Pull request by asingamaneni**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**
This pr add the `materical-plausible` to mkdocs, which provides analytics and takes feedbacks from the user. 
This pr addresses #191

### CODE REVIEW

**Review by MrPowers — APPROVED** [review]
LGTM

**Comment by asingamaneni** [comment]
> LGTM

I am not able to merge this pr, can you please merge it!

**Comment by vikrantpuppala** [comment]
@haogang to merge

**Comment by cjyabraham** [comment]
I would suggest you proxy the Plausible script using [this method](https://plausible.io/docs/proxy/introduction#are-you-concerned-about-missing-data) to avoid missing a large chunk of your traffic.

**Pull request merged**
