### PR TITLE
adjust --help messages in uc cli

### PR DESCRIPTION
**Pull request by Marcinx26**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

Hi,

This is my first PR, so I would like to say hello and highlight that this PR probably needs some attention. :)

Changes:

1. Added a new entry, `CliParams`, to distinguish between `schema_full_name` for schema (which consists of two levels: `catalog.schema`) and 'full_name" for other objects (table/function/schema with a three-level name like `catalog.schema.object`).
2. `printSubCommandHelp` now prints common parameters, including `--output`, `--server`, and `--token`.
3. Minor fixes to messages used in `--help`.

The code in this PR changes `full_name` to `schema_full_name`, which may be a breaking change. We need to consider whether this is the best option or if we should stick to `full_name` in all cases and find an alternative solution.

Issue: [253](https://github.com/unitycatalog/unitycatalog/issues/253)

### CODE REVIEW

**Comment by vikrantpuppala** [comment]
I'm not entirely convinced on why we need to change the option from `full_name` to `schema_full_name`, I feel it might add to more confusion (and more options to remember) + feels like `full_name` when used in schema context (i.e. `bin/uc schema get ...`) is quite self explanatory. Would like to know your view point.

**Comment by Marcinx26** [comment]
> I'm not entirely convinced on why we need to change the option from `full_name` to `schema_full_name`, I feel it might add to more confusion (and more options to remember) + feels like `full_name` when used in schema context (i.e. `bin/uc schema get ...`) is quite self explanatory. Would like to know your view point.

Initially, my point was to differentiate between 3rd level objects and schema, which is at the 2nd level. For me, it was misleading when I tried to handle both schema and tables with the same full_name and the same description. It would also be easier to navigate in the code with separate constants for 1st level name (catalog), 2nd level (schema), and 3rd level (function/table/volume).

I understand your point, and in my opinion, we can stick to full_name to keep things simpler (as no changes in commands are required). My proposition for the full_name message is:

"The full name in the format catalog_name.schema_name for schema, or catalog_name.schema_name.table_name for table/function/volume"

Sample output after my changes:

> Usage: bin/uc schema get [options]
> Required Params:
>   --full_name The full name in the format catalog_name.schema_name for schema, or catalog_name.schema_name.table_name for table/function/volume
> Optional Params:
>   --server UC Server to connect to. Default is reference server.
>   --auth_token PAT token to authorize uc requests.
>   --output To indicate CLI output format preference. Supported values are json and jsonPretty.
>

**Comment by vikrantpuppala** [comment]
Agree with changing the message 👍 
thank you

**Review by vikrantpuppala — APPROVED** [review]
lgtm @haogang to merge

**Review by haogang — APPROVED** [review]

**Pull request merged**
