### PR TITLE
Fix next page token

### PR DESCRIPTION
**Pull request by abrassel**
## PR Checklist

- [X] A description of the changes is added to the description of this PR.
- [X] If there is a related issue, make sure it is linked to this PR.
- [X] If you've fixed a bug or added code that should be tested, add tests!

## Description of changes

Addresses #21 

When performing a tables.list operation, it seems that the server returns the empty string "" instead of None as documented in the spec.

Fixed this by making the paginated request return `null` instead.

## Testing

On a default run of unity catalog, did this manual test:
```
import unitycatalog

client = unitycatalog.Unitycatalog(base_url="http://127.0.0.1:8080/api/2.1/unity-catalog/")
response = client.tables.list(catalog_name="unity", schema_name="default")

assert response.next_page_token is None, f"This will fail, with a non-empty token: {response.next_page_token}"

response = client.tables.list(catalog_name="unity", schema_name="default", page_token=response.next_page_token)
assert len(response.tables) > 0, "This will fail, because response has no tables"
assert response.next_page_token is None
```

Any tips for testing this effectively?

### CODE REVIEW

**Comment by abrassel** [comment]
@tdas can you review this PR?

**Review by ramesh-db — APPROVED** [review]
@abrassel thank you for fixing this.

Can you add a test for the fix? Will merge after the test.

**Comment by abrassel** [comment]
@ramesh-db Thanks for the review! Do you have a code pointer for this repo's testing framework?

**Review by Fokko — APPROVED** [review]

**Comment by ravivj-db** [comment]
Hi @abrassel , you can checkout the file BaseTableCRUDTest and SdkTableCRUDTest. Ideally we would have wanted to add this check directly to the BaseTableCRUDTest, however we have currently kept the return type of `listTables` as  List<TableInfo> (which omits the next page token)  to keep compatibility between Sdk and Cli Tests (in CLI we are not handling next page tokens). A workaround would be to create a small ListTablesTest at the level of SdkTableCRUDTest (which directly extends BaseCRUDTest or BaseServerTest) and just creates a couple of tables and Tests the output of the listTables. Then it can read the response as `ListTableResponse` and check the `nextPageToken` field.

**Comment by abrassel** [comment]
Hi @ramesh-db I added a test. We should be good to go now.

**Review by tdas — APPROVED** [review]

**Pull request merged**
