### PR TITLE
Expose and Publish default port 8080 for start-uc-server-docker.

### PR DESCRIPTION
**Pull request by yaoderek**
**PR Checklist**

- [X] A description of the changes is added to the description of this PR.
- [ ] If there is a related issue, make sure it is linked to this PR.
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

By default, uc-server runs on ports 8080 (transcode) and 8081. 
Without --server argument, UC CLI/UI only connects to the transcode port 8080 by default. 

This change is to expose both port 8080/8081 in start-uc-server-docker so that 
* Users following documents (default: 8080) won't fail to connect the server running in docker. 
* CLI/UI won't need to specify --server argument. 

### Before the Fix:

```
derek@dev-linux unitycatalog (docker_expose) $ docker/bin/start-uc-server-docker 
❤️ Starting unitycatalog:0.2.0-SNAPSHOT.
💡 Use Ctrl+C to stop and remove the container.
...


derek@dev-linux unitycatalog (docker_expose) $ ./bin/uc catalog list --server http://localhost:8081

┌─────┬────────────┬──────────┬─────────────┬──────────┬────────────────────────────────────┐
│NAME │  COMMENT   │PROPERTIES│ CREATED_AT  │UPDATED_AT│                 ID                 │
├─────┼────────────┼──────────┼─────────────┼──────────┼────────────────────────────────────┤
│unity│Main catalog│{}        │1721241605334│null      │f029b870-9468-4f10-badc-630b41e5690d│
└─────┴────────────┴──────────┴─────────────┴──────────┴────────────────────────────────────┘


derek@dev-linux unitycatalog (docker_expose) $ ./bin/uc catalog list
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: java.net.ConnectException
        at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:165)
Caused by: io.unitycatalog.client.ApiException: java.net.ConnectException
...
```

### After the Fix.
```
derek@dev-linux unitycatalog (docker_expose) $ ./bin/uc catalog list

┌─────┬────────────┬──────────┬─────────────┬──────────┬────────────────────────────────────┐
│NAME │  COMMENT   │PROPERTIES│ CREATED_AT  │UPDATED_AT│                 ID                 │
├─────┼────────────┼──────────┼─────────────┼──────────┼────────────────────────────────────┤
│unity│Main catalog│{}        │1721241605334│null      │f029b870-9468-4f10-badc-630b41e5690d│
└─────┴────────────┴──────────┴─────────────┴──────────┴────────────────────────────────────┘
```

### CODE REVIEW

**Comment by VillePuuska** [comment]
Maybe 8080 should also be exposed in the Dockerfile?

**Comment by jaceklaskowski** [comment]
Please add `EXPOSE 8080` to the `Dockerfile` as @VillePuuska mentioned 🙏

**Review by jaceklaskowski — APPROVED** [review]
LGTM

**Comment by jaceklaskowski** [comment]
Hey @dennyglee, may I ask you to review the changes (and hopefully approve)? 🙏

**Review by dennyglee — APPROVED** [review]
Thanks @yaoderek and appreciate the ping @jaceklaskowski

**Review by dennyglee — APPROVED** [review]

**Comment by dennyglee** [comment]
This looks great @yaoderek !  Approving and merging now.  By any chance would you be able to update it so that way the UI service is running from the docker and we can access the UI running from that docker?

**Comment by yaoderek** [comment]
@dennyglee Thanks for reviewing and merging my PR. This issue was originally found when I tried the new UI. 
I verified after this fix, new UI can access unity-catalog running in the container without any additional changes.

**Pull request merged**
