### PR TITLE
Add CelerData Integration documentation to navigation

### LINKED ISSUE #670: Add CelerData Integration documentation to navigation
**Is your feature request related to a problem? Please describe.**

Currently the CelerData Integration documentation, located at `docs/integrations/unity-catalog-celerdata.md`, is missing from the navigation and with that from the documentation.

**Describe the solution you would like**

Add it to the `mkdocs.yml` configuration.

**Additional context**

See comment in #572 for details.

### PR DESCRIPTION
**Pull request by HorizonNet**
**PR Checklist**

- [x] A description of the changes is added to the description of this PR.
- [x] If there is a related issue, make sure it is linked to this PR.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**

Added the CelerData Integration documentation to the navigation in MkDocs to be displayed in the published documentation version.

Resolves #670

### CODE REVIEW

**Review by dennyglee — APPROVED** [review]
thanks @HorizonNet !

**Comment by dennyglee** [comment]
Sorry @HorizonNet - could you check why this branch has conflicts?  Thanks!

**Comment by HorizonNet** [comment]
@dennyglee Merge conflicts are resolved.

**Comment by dennyglee** [comment]
Thanks again @HorizonNet !

**Pull request merged**
